<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function run(): void
    {
        $cities = [
            'CHICHAOUA',
            'MIDELT',
            'KELAA MAGOUNA',
            'LALLA MIMOUNA',
            'SKHOUR REHAMNA',
            'BOUJDOUR',
            'YOUSSOUFIA',
            'RICH',
            'SIDI YAHYA ZAER',
            'OUAHAT SIDI BRAHIM',
            'SABAA LAYOUNE',
            'SOUIHLA',
            'ZAYDA',
            'MARRAKECH',
            'OURIKA',
            'MARZOUGA',
            'OUDAYA MARRAKECH',
            'ERRACHIDIA',
            'TAHANNAOUT',
            'TAGOUNITE ZAGORA',
            'AL ARJAT',
            'MOULAY BOUSSELHAM',
            'TAMELLALT',
            'SIDI ALLAL TAZI',
            'BEN GUERIR',
            'LAAYOUNE MARSA',
            'AHFIR I',
            'SOUK ELARBAA DU GHARB',
            'EL ATTAOUIA',
            'IMOUZZER MARMOUCHA',
            'SIDI BIBI',
            'PLAGE DAVIDE',
            'AIN CHKEF',
            'BARICHINO',
            'OULAD DRISS',
            'RAS EL MA -FES',
            'AIN ATTIG',
            'HED OULED FREJ',
            'CABO NEGRO',
            'SIDI ABED',
            'TIGHSALIN',
            'OUED LAOU',
            'TAGHAZOUT',
            'ALMAZ',
            'TAFRAWT',
            'SELOUANE',
            'KRAZA',
            'IMOUZZER KANDAR FES',
            'AHFIR',
            'ZAWIT CHIKH',
            'GUEZNAIA',
            'HAOUZIA',
            'HATTAN',
            'OUNNANA',
            'MEKNES',
            'SIDI MASSOUD',
            'MASSA',
            'BEN HMED (CASABLANCA)',
            'AZROU',
            'MIDAR',
            'MGHILA',
            'SABAA AIYOUN-MEKNES',
            'AIN EL AOUDA',
            'ESSAOUIRA',
            'KABILA',
            'HAD OULAD FREJ',
            'OUAOUMANA',
            'BRIKCHA',
            'AZROU (souss)',
            'BOUSEKOURA',
            'TATA',
            'ZEGHANGHANE',
            'BENI AYAT',
            'KHEMISSET',
            'TANDRARA',
            'IGHRAL LAALAM',
            'MARTIL',
            'KHEMISS ZEMAMRA',
            'OUED ZEM',
            'AJDIR HOCEIMA',
            'INEZGANE',
            'VILLE VERTE',
            'HOUARA',
            'BEN SLIMANE',
            'BOUFAKRANE',
            'TAFARSIT',
            'ZWAYR',
            'SIDI HARAZEM',
            'TAMESNA',
            'YOUSSOUFIA',
            'AL HOCEIMA',
            'GHADBAN',
            'EL JEBEHA',
            'LQLIAA',
            'TAMARIS',
            'FOUM ZKID',
            'FARKHANA',
            'DAR OULED ZIDOH',
            'MISSOUR',
            'AIN BENI MATHAR',
            'FOM ZAWIA',
            'TETOUAN',
            'SIDI ALI AZEMMOUR',
            'TACHRAFT',
            'TARGUIST',
            'AIT MELLOUL',
            'LIIRAKI (CASABLANCA)',
            'TALIWIN',
            'OULAD MOUSSA',
            'DOUIYAT',
            'TAMSAMANE',
            'OULAD SAID',
            'TAOUNATE',
            'BOUKNADEL',
            'ECHAMAIA',
            'AZLA',
            'ARBA AOUNATE',
            'ALANSSAR',
            'LMZAR',
            'MEDIOUNA',
            'AGOURAY',
            'JAADAR',
            'SOUK SEBT',
            'MOULAY YACOUB',
            'BOUARFA',
            'TAGZIRT',
            'BOUANANE TETOUN',
            'HAD SOUALEM',
            'KHENIFRA',
            'IMZOUREN',
            'ANZA',
            'ERRAHMA',
            'SABT LKARDAN',
            'SIDI ISSA',
            'EL HAJEB',
            'BERKANE',
            'AIT RBAA',
            'TAOURIRT',
            'TIFLET',
            'WAWIZGHT',
            'AIN DORIJ',
            'TNIN GHARBIA',
            'BEN AHMED (nord)',
            'BIOUGRA',
            'DAR BOUAZZA',
            'AIB BIDA',
            'ZAIO',
            'FKIH BEN SALAH',
            'OULAD TAYEB-FES',
            'SALE EL JADIDA',
            'HAWZIA',
            'FNIDEQ',
            'TNINE CHTOUKA',
            'MRIRT',
            'BAB TAZA',
            'AOURIR',
            'BENI YKHLEF',
            'SIDI IFNI',
            'NADOR',
            'FOM OUDI',
            'HAJ KADDOUR',
            'SAIDIA',
            'KAMOUN',
            'LAAYOUNE SIDI MELOUK',
            'MOULAY ABDELAH',
            'KHOURIBGUA',
            'KSAR SGHIR',
            'CASABLANCA',
            'CHRAFAT CHEFCHAOUEN',
            'BELKSIRI',
            'DEMNATE',
            'ROMANI',
            'IMINTANOUTE',
            'DAKHLA',
            'SIDI SLIMANE',
            'MZOUDIA',
            'LAHRAOUIYINE',
            'TAMANSOURT',
            'BEN GUERIR',
            'SIDI YAHYA GHARB',
            'SID ZOUINE',
            'SABT GARDAN',
            'SIDI ABDELLAH GHIAT',
            'GUELMIM',
            'AIT OURIR',
            'ZAGORA',
            'tinghir',
            'HARHOURA',
            'SID L MOKHTAR',
            'OUARZAZATE',
            'TAMESLUHT',
            'LAAYOUNE',
            'TARFAYA',
            'SIDI ALLAL EL BAHRAOUI',
            'SIDI BOU OTHMANE',
            'SMARA',
            'EL KELAA DES SRAGHNA',
            'SIDI KACEM',
        ];


        foreach ($cities as $city) {
            DB::table('cities')->updateOrInsert(
                ['name' => trim($city), 'country_id' => 1],
                [
                    'updated_at' => now(),
                    'created_at' => now(),
                ]
            );
        }
    }
}
